import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/Footer";
import HeaderWithWebSocket from '../components/HeaderWithWebSocket';
import MobileLayoutHandler from '../components/MobileLayoutHandler';
import MobileHeader from '../components/MobileHeader';
import MobileFooter from '../components/MobileFooter';
import MobileProviders from '../components/MobileProviders';
import ErrorContainer from '../components/ErrorContainer';
import { ErrorProvider } from '../context/ErrorContext';
import AdSenseManager from '../components/AdSenseManager';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GiveNGet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ 
          minHeight: '100vh', 
          display: 'flex', 
          flexDirection: 'column',
          margin: 0 
        }}
      >
        <ErrorProvider>
          <AdSenseManager>
            <ErrorContainer />
            <MobileLayoutHandler />
            <div className="mobile-layout">
              <MobileProviders>
                <MobileHeader />
                <main className="mobile-main">
                  {children}
                </main>
                <MobileFooter />
              </MobileProviders>
            </div>
            <div className="desktop-layout">
              <HeaderWithWebSocket>
                <main style={{ flex: 1 }}>
                  {children}
                </main>
                <Footer />
              </HeaderWithWebSocket>
            </div>
          </AdSenseManager>
        </ErrorProvider>
      </body>
    </html>
  );
}