INSERT INTO forbidden_pattern(pattern, type, category, active) VALUES
('kurwa', 'WORD', 'WULGARYZMY', TRUE),
('kurwy', 'WORD', 'WULGARYZMY', TRUE),
('kurew', 'WORD', 'WULGARYZMY', TRUE),
('kurewski', 'WORD', 'WULGARYZMY', TRUE),
('kurewstwo', 'WORD', 'WULGARYZMY', TRUE),
('kurwisko', 'WORD', 'WULGARYZMY', TRUE),
('skurwysyn', 'WORD', 'WULGARYZMY', TRUE),
('skurwiel', 'WORD', 'WULGARYZMY', TRUE),
('skurw*', 'WORD', 'WULGARYZMY', TRUE),
('skurwić', 'WORD', 'WULGARYZMY', TRUE),
('pojeb', 'WORD', 'WULGARYZMY', TRUE),
('poj**any', 'WORD', 'WULGARYZMY', TRUE),
('jebany', 'WORD', 'WULGARYZMY', TRUE),
('jebac', 'WORD', 'WULGARYZMY', TRUE),
('jebane', 'WORD', 'WULGARYZMY', TRUE),
('pierd**', 'WORD', 'WULGARYZMY', TRUE),
('spierd*', 'WORD', 'WULGARYZMY', TRUE),
('spierdalaj', 'WORD', 'WULGARYZMY', TRUE),
('wypierdalaj', 'WORD', 'WULGARYZMY', TRUE),
('wypierdol', 'WORD', 'WULGARYZMY', TRUE),
('wyjeb', 'WORD', 'WULGARYZMY', TRUE),
('wyjebany', 'WORD', 'WULGARYZMY', TRUE),
('chuj', 'WORD', 'WULGARYZMY', TRUE),
('chuje', 'WORD', 'WULGARYZMY', TRUE),
('chuja', 'WORD', 'WULGARYZMY', TRUE),
('chujnia', 'WORD', 'WULGARYZMY', TRUE),
('kutas', 'WORD', 'WULGARYZMY', TRUE),
('kutasa', 'WORD', 'WULGARYZMY', TRUE),
('kutasy', 'WORD', 'WULGARYZMY', TRUE),
('pizda', 'WORD', 'WULGARYZMY', TRUE),
('pizdy', 'WORD', 'WULGARYZMY', TRUE),
('pizdka', 'WORD', 'WULGARYZMY', TRUE),
('cipa', 'WORD', 'WULGARYZMY', TRUE),
('cipy', 'WORD', 'WULGARYZMY', TRUE),
('cipka', 'WORD', 'WULGARYZMY', TRUE),
('cipki', 'WORD', 'WULGARYZMY', TRUE),
('cipcia', 'WORD', 'WULGARYZMY', TRUE),
('ciota', 'WORD', 'WULGARYZMY', TRUE),
('frajer', 'WORD', 'WULGARYZMY', TRUE),
('frajerski', 'WORD', 'WULGARYZMY', TRUE),
('frajerstwo', 'WORD', 'WULGARYZMY', TRUE),
('lamus', 'WORD', 'WULGARYZMY', TRUE),
('gówno', 'WORD', 'WULGARYZMY', TRUE),
('gowno', 'WORD', 'WULGARYZMY', TRUE),
('gowniany', 'WORD', 'WULGARYZMY', TRUE),
('gnój', 'WORD', 'WULGARYZMY', TRUE),
('baran', 'WORD', 'WULGARYZMY', TRUE),
('idiota', 'WORD', 'WULGARYZMY', TRUE),
('idioci', 'WORD', 'WULGARYZMY', TRUE),
('idiotka', 'WORD', 'WULGARYZMY', TRUE),
('kretyn', 'WORD', 'WULGARYZMY', TRUE),
('kretyni', 'WORD', 'WULGARYZMY', TRUE),
('kretynka', 'WORD', 'WULGARYZMY', TRUE),
('debil', 'WORD', 'WULGARYZMY', TRUE),
('debile', 'WORD', 'WULGARYZMY', TRUE),
('debilka', 'WORD', 'WULGARYZMY', TRUE),
('tępak', 'WORD', 'WULGARYZMY', TRUE),
('głupi', 'WORD', 'WULGARYZMY', TRUE),
('głupol', 'WORD', 'WULGARYZMY', TRUE),
('osioł', 'WORD', 'WULGARYZMY', TRUE),
('szmata', 'WORD', 'WULGARYZMY', TRUE),
('szmaty', 'WORD', 'WULGARYZMY', TRUE),
('suka', 'WORD', 'WULGARYZMY', TRUE),
('suki', 'WORD', 'WULGARYZMY', TRUE),
('dziwka', 'WORD', 'WULGARYZMY', TRUE),
('dziwkarz', 'WORD', 'WULGARYZMY', TRUE),
('dziwkarstwo', 'WORD', 'WULGARYZMY', TRUE),
('alfons', 'WORD', 'WULGARYZMY', TRUE),
('alfonsiara', 'WORD', 'WULGARYZMY', TRUE),
('ruchać', 'WORD', 'WULGARYZMY', TRUE),
('ruchanie', 'WORD', 'WULGARYZMY', TRUE),
('ruchanko', 'WORD', 'WULGARYZMY', TRUE),
('dymać', 'WORD', 'WULGARYZMY', TRUE),
('walić konia', 'WORD', 'WULGARYZMY', TRUE),
('walić gruchę', 'WORD', 'WULGARYZMY', TRUE),
('grucha', 'WORD', 'WULGARYZMY', TRUE),
('masturbacja', 'WORD', 'WULGARYZMY', TRUE),
('masturbować się', 'WORD', 'WULGARYZMY', TRUE),
('onanizować się', 'WORD', 'WULGARYZMY', TRUE),
('pedał', 'WORD', 'WULGARYZMY', TRUE),
('pedaly', 'WORD', 'WULGARYZMY', TRUE),
('pedały', 'WORD', 'WULGARYZMY', TRUE),
('lesba', 'WORD', 'WULGARYZMY', TRUE),
('lesbijka', 'WORD', 'WULGARYZMY', TRUE),
('homoseks', 'WORD', 'WULGARYZMY', TRUE),
('pedalstwo', 'WORD', 'WULGARYZMY', TRUE),
('/k[uüv][r]+w[a@4ą]/i', 'REGEX', 'WULGARYZMY', TRUE),
('/poj[e3]b[a@4ą]n[y¥j]/i', 'REGEX', 'WULGARYZMY', TRUE),
('/j[e3]b[a@4ą]c/i', 'REGEX', 'WULGARYZMY', TRUE),
('/p[i1!|][z2][d][a@4ą]/i', 'REGEX', 'WULGARYZMY', TRUE),
('/c[i1!|]p[a@4ą]/i', 'REGEX', 'WULGARYZMY', TRUE),
('/ch[uüv]j/i', 'REGEX', 'WULGARYZMY', TRUE),
('/sk[uüv]rw[y¥j]s[y¥j]n/i', 'REGEX', 'WULGARYZMY', TRUE),
('/p[i1!|]erdol/i', 'REGEX', 'WULGARYZMY', TRUE),
('/sp[i1!|]erdal[a@4ą]j/i', 'REGEX', 'WULGARYZMY', TRUE),

('narkotyk', 'WORD', 'NARKOTYKI', TRUE),
('narkotyki', 'WORD', 'NARKOTYKI', TRUE),
('ćpanie', 'WORD', 'NARKOTYKI', TRUE),
('ćpać', 'WORD', 'NARKOTYKI', TRUE),
('ćpun', 'WORD', 'NARKOTYKI', TRUE),
('ćpuny', 'WORD', 'NARKOTYKI', TRUE),
('koka', 'WORD', 'NARKOTYKI', TRUE),
('kokaina', 'WORD', 'NARKOTYKI', TRUE),
('coke', 'WORD', 'NARKOTYKI', TRUE),
('crack', 'WORD', 'NARKOTYKI', TRUE),
('heroina', 'WORD', 'NARKOTYKI', TRUE),
('brown sugar', 'WORD', 'NARKOTYKI', TRUE),
('LSD', 'WORD', 'NARKOTYKI', TRUE),
('acid', 'WORD', 'NARKOTYKI', TRUE),
('kwas', 'WORD', 'NARKOTYKI', TRUE),
('grzyby halucynogenne', 'WORD', 'NARKOTYKI', TRUE),
('magic mushrooms', 'WORD', 'NARKOTYKI', TRUE),
('psylocybina', 'WORD', 'NARKOTYKI', TRUE),
('amfetamina', 'WORD', 'NARKOTYKI', TRUE),
('amfa', 'WORD', 'NARKOTYKI', TRUE),
('speed', 'WORD', 'NARKOTYKI', TRUE),
('meta', 'WORD', 'NARKOTYKI', TRUE),
('metamfetamina', 'WORD', 'NARKOTYKI', TRUE),
('ice', 'WORD', 'NARKOTYKI', TRUE),
('crystal', 'WORD', 'NARKOTYKI', TRUE),
('kryształ', 'WORD', 'NARKOTYKI', TRUE),
('meth', 'WORD', 'NARKOTYKI', TRUE),
('mdma', 'WORD', 'NARKOTYKI', TRUE),
('ecstasy', 'WORD', 'NARKOTYKI', TRUE),
('piguły', 'WORD', 'NARKOTYKI', TRUE),
('tabs', 'WORD', 'NARKOTYKI', TRUE),
('tripy', 'WORD', 'NARKOTYKI', TRUE),
('dopalacze', 'WORD', 'NARKOTYKI', TRUE),
('dopalacz', 'WORD', 'NARKOTYKI', TRUE),
('joint', 'WORD', 'NARKOTYKI', TRUE),
('blunt', 'WORD', 'NARKOTYKI', TRUE),
('blant', 'WORD', 'NARKOTYKI', TRUE),
('skręt', 'WORD', 'NARKOTYKI', TRUE),
('spliff', 'WORD', 'NARKOTYKI', TRUE),
('weed', 'WORD', 'NARKOTYKI', TRUE),
('marihuana', 'WORD', 'NARKOTYKI', TRUE),
('maryśka', 'WORD', 'NARKOTYKI', TRUE),
('zioło', 'WORD', 'NARKOTYKI', TRUE),
('ganja', 'WORD', 'NARKOTYKI', TRUE),
('cannabis', 'WORD', 'NARKOTYKI', TRUE),
('konopie', 'WORD', 'NARKOTYKI', TRUE),
('thc', 'WORD', 'NARKOTYKI', TRUE),
('hash', 'WORD', 'NARKOTYKI', TRUE),
('hasz', 'WORD', 'NARKOTYKI', TRUE),
('haszysz', 'WORD', 'NARKOTYKI', TRUE),
('olej thc', 'WORD', 'NARKOTYKI', TRUE),
('olej haszyszowy', 'WORD', 'NARKOTYKI', TRUE),
('vaporizer', 'WORD', 'NARKOTYKI', TRUE),
('vape', 'WORD', 'NARKOTYKI', TRUE),
('e-joint', 'WORD', 'NARKOTYKI', TRUE),
('koktajl narkotykowy', 'WORD', 'NARKOTYKI', TRUE),
('/amf[a@4ą]/i', 'REGEX', 'NARKOTYKI', TRUE),
('/kok[a@4ą][i1!|]n[a@4ą]/i', 'REGEX', 'NARKOTYKI', TRUE),
('/h[e3]ro[i1!|]n[a@4ą]/i', 'REGEX', 'NARKOTYKI', TRUE),
('/l[s5$]d/i', 'REGEX', 'NARKOTYKI', TRUE),
('/w[e3€]ed/i', 'REGEX', 'NARKOTYKI', TRUE),
('/j[o0]?[i1!|]nt/i', 'REGEX', 'NARKOTYKI', TRUE),
('/marihu[a@4ą]n[a@4ą]/i', 'REGEX', 'NARKOTYKI', TRUE),
('/dopalacz[e3]?/i', 'REGEX', 'NARKOTYKI', TRUE),

('broń', 'WORD', 'BRON', TRUE),
('bron', 'WORD', 'BRON', TRUE),
('broń palna', 'WORD', 'BRON', TRUE),
('karabin', 'WORD', 'BRON', TRUE),
('karabinek', 'WORD', 'BRON', TRUE),
('pistolet', 'WORD', 'BRON', TRUE),
('pistolety', 'WORD', 'BRON', TRUE),
('rewolwer', 'WORD', 'BRON', TRUE),
('rewolwery', 'WORD', 'BRON', TRUE),
('strzelba', 'WORD', 'BRON', TRUE),
('shotgun', 'WORD', 'BRON', TRUE),
('ak47', 'WORD', 'BRON', TRUE),
('kałasznikow', 'WORD', 'BRON', TRUE),
('granat', 'WORD', 'BRON', TRUE),
('granaty', 'WORD', 'BRON', TRUE),
('dynamit', 'WORD', 'BRON', TRUE),
('TNT', 'WORD', 'BRON', TRUE),
('bomba', 'WORD', 'BRON', TRUE),
('materiały wybuchowe', 'WORD', 'BRON', TRUE),
('semtex', 'WORD', 'BRON', TRUE),
('C4', 'WORD', 'BRON', TRUE),
('nóż sprężynowy', 'WORD', 'BRON', TRUE),
('noże sprężynowe', 'WORD', 'BRON', TRUE),
('maczeta', 'WORD', 'BRON', TRUE),
('bagnet', 'WORD', 'BRON', TRUE),
('pałka teleskopowa', 'WORD', 'BRON', TRUE),
('taser', 'WORD', 'BRON', TRUE),
('paralizator', 'WORD', 'BRON', TRUE),
('kastet', 'WORD', 'BRON', TRUE),
('amunicja', 'WORD', 'BRON', TRUE),
('naboje', 'WORD', 'BRON', TRUE),
('magazynek', 'WORD', 'BRON', TRUE),
('pociski', 'WORD', 'BRON', TRUE),
('rakieta', 'WORD', 'BRON', TRUE),
('miny', 'WORD', 'BRON', TRUE),
('granatnik', 'WORD', 'BRON', TRUE),
('wyrzutnia rakiet', 'WORD', 'BRON', TRUE),
('moździerz', 'WORD', 'BRON', TRUE),
('broń chemiczna', 'WORD', 'BRON', TRUE),
('gaz bojowy', 'WORD', 'BRON', TRUE),
('gaz łzawiący', 'WORD', 'BRON', TRUE),
('miotacz ognia', 'WORD', 'BRON', TRUE),
('broń biologiczna', 'WORD', 'BRON', TRUE),
('napalm', 'WORD', 'BRON', TRUE),
('trucizna', 'WORD', 'BRON', TRUE),

('/pisto[l1!]et/i', 'REGEX', 'BRON', TRUE),
('/karab[i1!|]n/i', 'REGEX', 'BRON', TRUE),
('/gran[a@4ą]t/i', 'REGEX', 'BRON', TRUE),
('/strzelb[a@4ą]/i', 'REGEX', 'BRON', TRUE),
('/b[o0]mb[a@4ą]/i', 'REGEX', 'BRON', TRUE),
('/n[a@4ą]b[o0]j[e3]/i', 'REGEX', 'BRON', TRUE),
('/kast[e3]t/i', 'REGEX', 'BRON', TRUE),
('/amunicj[a@4ą]/i', 'REGEX', 'BRON', TRUE),

('porno', 'WORD', 'SEKS', TRUE),
('porn', 'WORD', 'SEKS', TRUE),
('pornki', 'WORD', 'SEKS', TRUE),
('pornole', 'WORD', 'SEKS', TRUE),
('pornografia', 'WORD', 'SEKS', TRUE),
('seks za darmo', 'WORD', 'SEKS', TRUE),
('sex randki', 'WORD', 'SEKS', TRUE),
('seks kamerki', 'WORD', 'SEKS', TRUE),
('sex kamerki', 'WORD', 'SEKS', TRUE),
('sex czat', 'WORD', 'SEKS', TRUE),
('sex chat', 'WORD', 'SEKS', TRUE),
('erotyka', 'WORD', 'SEKS', TRUE),
('xxx', 'WORD', 'SEKS', TRUE),
('sex ogłoszenia', 'WORD', 'SEKS', TRUE),
('sex anonse', 'WORD', 'SEKS', TRUE),
('prostytutka', 'WORD', 'SEKS', TRUE),
('prostytucja', 'WORD', 'SEKS', TRUE),
('call girl', 'WORD', 'SEKS', TRUE),
('callboy', 'WORD', 'SEKS', TRUE),
('escort', 'WORD', 'SEKS', TRUE),
('sex escort', 'WORD', 'SEKS', TRUE),
('anal', 'WORD', 'SEKS', TRUE),
('analny', 'WORD', 'SEKS', TRUE),
('anal fuck', 'WORD', 'SEKS', TRUE),
('gangbang', 'WORD', 'SEKS', TRUE),
('orgia', 'WORD', 'SEKS', TRUE),
('orgie', 'WORD', 'SEKS', TRUE),
('fetysz', 'WORD', 'SEKS', TRUE),
('fetysze', 'WORD', 'SEKS', TRUE),
('bdsm', 'WORD', 'SEKS', TRUE),
('sado maso', 'WORD', 'SEKS', TRUE),
('dominacja', 'WORD', 'SEKS', TRUE),
('niewolnica sex', 'WORD', 'SEKS', TRUE),
('sex niewolnik', 'WORD', 'SEKS', TRUE),
('dildo', 'WORD', 'SEKS', TRUE),
('wibrator', 'WORD', 'SEKS', TRUE),
('sextoy', 'WORD', 'SEKS', TRUE),
('kamasutra', 'WORD', 'SEKS', TRUE),
('pornohub', 'WORD', 'SEKS', TRUE),
('redtube', 'WORD', 'SEKS', TRUE),
('xvideos', 'WORD', 'SEKS', TRUE),
('xnxx', 'WORD', 'SEKS', TRUE),
('porno polskie', 'WORD', 'SEKS', TRUE),
('filmy porno', 'WORD', 'SEKS', TRUE),
('pedofil', 'WORD', 'SEKS', TRUE),
('pedofilia', 'WORD', 'SEKS', TRUE),
('child porn', 'WORD', 'SEKS', TRUE),
('gwałt', 'WORD', 'SEKS', TRUE),
('gwałcić', 'WORD', 'SEKS', TRUE),
('gwałciciel', 'WORD', 'SEKS', TRUE),
('molestowanie', 'WORD', 'SEKS', TRUE),
('molestować', 'WORD', 'SEKS', TRUE),
('molest', 'WORD', 'SEKS', TRUE),
('gwałt zbiorowy', 'WORD', 'SEKS', TRUE),

('/p[o0]rn[o0]?/i', 'REGEX', 'SEKS', TRUE),
('/sex/i', 'REGEX', 'SEKS', TRUE),
('/erot[y¥j]k[a@4ą]/i', 'REGEX', 'SEKS', TRUE),
('/d[i1!|]ld[o0]/i', 'REGEX', 'SEKS', TRUE),
('/wibr[a@4ą]t[o0]r/i', 'REGEX', 'SEKS', TRUE),
('/anal/i', 'REGEX', 'SEKS', TRUE),
('/gangb[a@4ą]ng/i', 'REGEX', 'SEKS', TRUE),
('/fetys[z2][e3]?/i', 'REGEX', 'SEKS', TRUE),
('/bdsm/i', 'REGEX', 'SEKS', TRUE),
('/p[e3]d[o0]f[i1!|]l/i', 'REGEX', 'SEKS', TRUE),
('/gwa[l1!]t/i', 'REGEX', 'SEKS', TRUE),
('/molest/i', 'REGEX', 'SEKS', TRUE),

('kasyno', 'WORD', 'HAZARD', TRUE),
('casino', 'WORD', 'HAZARD', TRUE),
('ruletka', 'WORD', 'HAZARD', TRUE),
('poker', 'WORD', 'HAZARD', TRUE),
('poker online', 'WORD', 'HAZARD', TRUE),
('black jack', 'WORD', 'HAZARD', TRUE),
('baccarat', 'WORD', 'HAZARD', TRUE),
('zakłady', 'WORD', 'HAZARD', TRUE),
('bukmacher', 'WORD', 'HAZARD', TRUE),
('buk', 'WORD', 'HAZARD', TRUE),
('betting', 'WORD', 'HAZARD', TRUE),
('bet', 'WORD', 'HAZARD', TRUE),
('obstawianie', 'WORD', 'HAZARD', TRUE),
('odds', 'WORD', 'HAZARD', TRUE),
('wygrana 100%', 'WORD', 'HAZARD', TRUE),
('wygrana gwarantowana', 'WORD', 'HAZARD', TRUE),
('szybka kasa', 'WORD', 'HAZARD', TRUE),
('szybki zarobek', 'WORD', 'HAZARD', TRUE),
('zarób 1000', 'WORD', 'HAZARD', TRUE),
('zarób szybko', 'WORD', 'HAZARD', TRUE),
('pasywny dochód', 'WORD', 'HAZARD', TRUE),
('piramida finansowa', 'WORD', 'HAZARD', TRUE),
('schemat ponzi', 'WORD', 'HAZARD', TRUE),
('forex scam', 'WORD', 'HAZARD', TRUE),
('crypto scam', 'WORD', 'HAZARD', TRUE),
('krypto oszustwo', 'WORD', 'HAZARD', TRUE),
('coin scam', 'WORD', 'HAZARD', TRUE),
('hazard online', 'WORD', 'HAZARD', TRUE),
('automaty hazardowe', 'WORD', 'HAZARD', TRUE),
('jednoręki bandyta', 'WORD', 'HAZARD', TRUE),
('gry hazardowe', 'WORD', 'HAZARD', TRUE),
('darmowe żetony kasyno', 'WORD', 'HAZARD', TRUE),
('darmowy bonus kasyno', 'WORD', 'HAZARD', TRUE),

('/kasyn[o0]/i', 'REGEX', 'HAZARD', TRUE),
('/casino/i', 'REGEX', 'HAZARD', TRUE),
('/pok[e3]r/i', 'REGEX', 'HAZARD', TRUE),
('/rul[e3]tk[a@4ą]/i', 'REGEX', 'HAZARD', TRUE),
('/obstawi[a@4ą]n/i', 'REGEX', 'HAZARD', TRUE),
('/bukmach[e3]r/i', 'REGEX', 'HAZARD', TRUE),
('/zar[o0]b/i', 'REGEX', 'HAZARD', TRUE),
('/piramid[a@4ą] fin[a@4ą]ns/i', 'REGEX', 'HAZARD', TRUE),

('kredyt bez bik', 'WORD', 'SPAM', TRUE),
('chwilówki 0%', 'WORD', 'SPAM', TRUE),
('darmowe pieniądze', 'WORD', 'SPAM', TRUE),
('darmowy kredyt', 'WORD', 'SPAM', TRUE),
('pożyczka bez zabezpieczeń', 'WORD', 'SPAM', TRUE),
('zarób bez pracy', 'WORD', 'SPAM', TRUE),
('magiczny lek', 'WORD', 'SPAM', TRUE),
('cudowna tabletka', 'WORD', 'SPAM', TRUE),
('szybkie odchudzanie', 'WORD', 'SPAM', TRUE),
('viagra bez recepty', 'WORD', 'SPAM', TRUE),
('cialis bez recepty', 'WORD', 'SPAM', TRUE),
('viagr', 'WORD', 'SPAM', TRUE),
('leki na potencję', 'WORD', 'SPAM', TRUE),
('leki na erekcję', 'WORD', 'SPAM', TRUE),
('testosteron w proszku', 'WORD', 'SPAM', TRUE),
('sterydy', 'WORD', 'SPAM', TRUE),
('anaboliki', 'WORD', 'SPAM', TRUE),
('anaboliczne', 'WORD', 'SPAM', TRUE),
('hormon wzrostu', 'WORD', 'SPAM', TRUE),
('HGH', 'WORD', 'SPAM', TRUE),
('doping', 'WORD', 'SPAM', TRUE),
('suplementy nielegalne', 'WORD', 'SPAM', TRUE),
('szczepionka fake', 'WORD', 'SPAM', TRUE),
('leczenie raka cudowne', 'WORD', 'SPAM', TRUE),
('cudowna terapia', 'WORD', 'SPAM', TRUE),

('telefon:', 'WORD', 'KONTAKT', TRUE),
('zadzwoń', 'WORD', 'KONTAKT', TRUE),
('sms na numer', 'WORD', 'KONTAKT', TRUE),
('napisz na whatsapp', 'WORD', 'KONTAKT', TRUE),
('napisz na telegram', 'WORD', 'KONTAKT', TRUE),
('napisz na signal', 'WORD', 'KONTAKT', TRUE),
('messenger prywatny', 'WORD', 'KONTAKT', TRUE),
('prywatny kontakt', 'WORD', 'KONTAKT', TRUE),
('poza aplikacją', 'WORD', 'KONTAKT', TRUE),
('skontaktuj się mailowo', 'WORD', 'KONTAKT', TRUE),
('@gmail.com', 'WORD', 'KONTAKT', TRUE),
('@yahoo.com', 'WORD', 'KONTAKT', TRUE),
('@onet.pl', 'WORD', 'KONTAKT', TRUE),
('@wp.pl', 'WORD', 'KONTAKT', TRUE),
('.pl', 'WORD', 'KONTAKT', TRUE),
('.com', 'WORD', 'KONTAKT', TRUE),
('http://', 'WORD', 'KONTAKT', TRUE),
('https://', 'WORD', 'KONTAKT', TRUE),
('www.', 'WORD', 'KONTAKT', TRUE),

('/@/i', 'REGEX', 'KONTAKT', TRUE),
('/http[s]?:\\/\\//i', 'REGEX', 'KONTAKT', TRUE),
('/www\\./i', 'REGEX', 'KONTAKT', TRUE),
('/telefon:?/i', 'REGEX', 'KONTAKT', TRUE),
('/whats[a@4ą]pp/i', 'REGEX', 'KONTAKT', TRUE),
('/t[e3]l[e3]gram/i', 'REGEX', 'KONTAKT', TRUE),
('/s[i1!]gn[a@4ą]l/i', 'REGEX', 'KONTAKT', TRUE),
('/m[e3]ss[e3]ng[e3]r/i', 'REGEX', 'KONTAKT', TRUE),

('handel organami', 'WORD', 'INNE', TRUE),
('sprzedaż organów', 'WORD', 'INNE', TRUE),
('organy do przeszczepu', 'WORD', 'INNE', TRUE),
('narządy ludzkie', 'WORD', 'INNE', TRUE),
('dzieci na sprzedaż', 'WORD', 'INNE', TRUE),
('handel dziećmi', 'WORD', 'INNE', TRUE),
('niewolnik', 'WORD', 'INNE', TRUE),
('handel ludźmi', 'WORD', 'INNE', TRUE),
('child trafficking', 'WORD', 'INNE', TRUE),
('human trafficking', 'WORD', 'INNE', TRUE),
('paszporty', 'WORD', 'INNE', TRUE),
('fałszywe dokumenty', 'WORD', 'INNE', TRUE),
('fake ID', 'WORD', 'INNE', TRUE),
('dowód osobisty do sprzedaży', 'WORD', 'INNE', TRUE),
('prawo jazdy do sprzedaży', 'WORD', 'INNE', TRUE),
('dokumenty fałszywe', 'WORD', 'INNE', TRUE),
('dyplom kupię', 'WORD', 'INNE', TRUE),
('prawo jazdy kupię', 'WORD', 'INNE', TRUE),

('/org[a@4ą]n[y¥j] d[o0] sprzed[a@4ą]ż/i', 'REGEX', 'INNE', TRUE),
('/narząd[y¥j]/i', 'REGEX', 'INNE', TRUE),
('/fa[l1!]szyw[e3] d[o0]kum[e3]nt[y¥j]/i', 'REGEX', 'INNE', TRUE),
('/fake id/i', 'REGEX', 'INNE', TRUE),
('/hand[e3]l lud[z2]/i', 'REGEX', 'INNE', TRUE),
('/ch[i1!]ld traffick/i', 'REGEX', 'INNE', TRUE);


