ALTER TABLE users ADD COLUMN create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN banned BOOLEAN DEFAULT FALSE;

UPDATE users SET create_date = NOW() WHERE create_date IS NULL;
